### ISSUE TITLE
bash profile order of precedent logic appears to still be wrong for linux

### ISSUE THREAD

**Issue by Marak** [hij1nx/complete#6]
Based on input from @tootallnate and @isaacs, it appears that the bash profile lookup is still not correct for linux. 

Based on this line ( https://github.com/hij1nx/complete/blob/master/lib/complete.js#L159)  it appears that `complete` can still take precedence over your more local bash profile if using a linux operating system.

**Comment by ELLIOTTCABLE** [comment]
Years later, I go googling around to figure out what on earth had added that section to my `~/.profile` without telling me (because I was pretty damn sure it wasn't *actually* Node.js that had done so — the text is very mis-leading, it should *definitely* include a link to this GitHub repository if nothing freaking else).

----

It's probably way too late to change anybody's mind or have any effect, here, but: here's another developer who stands by @isaacs' arguments 100%. It's *disgusting* to have something modify my dotfiles, *especially* the very personal and crucial shell profiles, without asking (or even notifying!) me.

I tend to try and not get offensive in technical discussions, but I think this merits that I be straightforward with my opinion:

GTFO my personal configuration scripts. /=

**Comment by hij1nx** [comment]
@ELLIOTTCABLE It does [`add a comment`](https://github.com/hij1nx/complete/blob/master/lib/complete.js#L243-L253) to specify what added code, you might have used a version at some point that did not.

If you don't like how this module works, or think you could improve it, you could do either two things: 1. make a PR or 2. make a suggestion for to improve it without being a jerk. Either way, telling someone to get the fuck out probably won't improve anything for anyone.
